// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igxzqabdagmcmftqwbfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlneHpxYWJkYWdtY21mdHF3YmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4NTk4NzcsImV4cCI6MjA5MjQzNTg3N30.TjK8oQXuenrPYoqSAIJ25XYIlmnHsMhofnaUgYa2g2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});